name: Build

run-name: ${{ github.actor }} is building the gradle project
on: [push]

jobs:
  build-software:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - run: ./gradlew build --no-daemon
